version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Porta do host mapeada para a aplicação
    environment:
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:h2:mem:usuarios
    restart: always # Garante que a aplicação reinicie caso falhe